@ExemploASP_NET_CORE_HostAddress = http://localhost:5226

GET {{ExemploASP_NET_CORE_HostAddress}}/weatherforecast/
Accept: application/json

#####################################################

###
#Testar GET
GET http://localhost:5226/Usuario
Accept: application/json

###
#Testar POST
Post http://localhost:5226/Usuario
Content-Type: application/json

{
    "Nome": "lucas",
    "Email": "lucas@gmail.com"
}

###
#Testar PUT
PUT http://localhost:5226/Usuario/1
Content-Type: application/json

{
    "Nome": "Leandro atualizado",
    "Email": "Leandro@gmail.com"
}

###
#Testar Delete
DELETE http://localhost:5226/Usuario/1

#####################################################